### ISSUE TITLE
HTTP Status 403

### ISSUE THREAD

**Issue by devLucasOAK** [arndom/octo-my-readme-workflow#1]
Wasup. I tried to use it following the README but didn't work for me

I'm getting this:

```log
Failed:  RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/arndom/octo-my-readme-workflow/v1/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/runner/work/_actions/arndom/octo-my-readme-workflow/v1/index.js:53:9 {
  status: 403,
  response: {
    url: 'https://api.github.com/repos/devLucasOAK/my-github-workflows/contents/my-octo-lang.png',
    status: 403,
    ...
```

I'm kinda new with this, but I'm guessing this is related to permissions to the target repo.
Related: https://github.com/actions/first-interaction/issues/10

Another issue is that is getting my top language wrong:

```log
Your top language is Java
java is a supported language ✅
```
But my unique language used in the repo is Python.

You can check my logs here:
https://github.com/devLucasOAK/my-github-workflows/actions/runs/4102396265

**Comment by arndom** [comment]
@devLucasOAK, 
- Regarding the second issue, this GitHub action fetches your most used language based on all your repos. What you are asking for is something I hadn't thought of doing, but it is a good feature. Feel free to let me know if you'd like to add the feature via a PR.

- For your first issue, yes, it is about permissions, Seems the workflow doesn't have write permission to your repo,
To change this, go to:

https://github.com/devLucasOAK/my-github-workflows/settings/actions

and select this: 
<img width="604" alt="image" src="https://user-images.githubusercontent.com/40564798/217007336-b4c6f67e-737f-4f16-aaba-97174540cec5.png">

alternatively, you could edit the workflow YAML, to allow write access for the `octo-my-readme-workflow` action specifically

**Comment by devLucasOAK** [comment]
That's it. worked well, thxx. it'd be good to add this in Readme as part of the steps.

About the top language, yeah.. kinda missunderstood at first but got it now. Perhaps I can try contribute further.

Congrats for the project, really interesting.
